# Generated by Django 4.1.6 on 2023-02-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stack',
            new_name='stock',
        ),
    ]
